### ISSUE TITLE
Pretrained weights for models mentioned in Table 2

### ISSUE THREAD

**Issue by HashmatShadab** [nmndeep/revisiting-at#3]
Can you please provide weights for other models mentioned in Table 2 such as ViT-S , ConvNeXt-T.  ViT-B and ConvNeXt-B(from Table 3)?

**Comment by nmndeep** [comment]
Hi, you can find these models at the following URL:
[https://nc.mlcloud.uni-tuebingen.de/index.php/s/XLLnoCnJxp74Zqn](https://nc.mlcloud.uni-tuebingen.de/index.php/s/XLLnoCnJxp74Zqn)

**Comment by HashmatShadab** [comment]
Thank you for sharing!

**Comment by HashmatShadab** [comment]
Are the clean pre-trained weights available for the ConvStem models?

**Comment by nmndeep** [comment]
Hi, the weight-links in the README table should also have clean CvSt checkpoints. Apart from these no other clean-CvSt models are available.
Hope this helps.
