### ISSUE TITLE
loading a pretrained chekpoint

### ISSUE THREAD

**Issue by royg27** [nmndeep/revisiting-at#7]
Hello,

First of all - thanks for the great work!
After downloading it from the link, I am trying to load a given checkpoint.
However, the load command fails - 
`torch.load('convnext_b_cvst_robust.pt', map_location='cpu')`
and outputs the following error:
`RuntimeError: Expected hasRecord("version") to be true, but got false`.
More details - I use the same torch version as required, and I have tried several different checkpoints.
How can I resolve this?

Thanks!

**Comment by nmndeep** [comment]
Hi,
Thanks for using our models, seems to be a version issue with torch.
Some people have reported this for other intances: [here](https://github.com/huggingface/pytorch-image-models/discussions/749)

I was able to load the same checkpoint in my current torch version, can you try with this?

![Screenshot 2024-02-27 at 10 56 43](https://github.com/nmndeep/revisiting-at/assets/21052187/46835c64-9a6c-488a-99b1-8ec633d9629d)

**Comment by royg27** [comment]
Thanks for your reply. I have tried your solution and a few other torch + cuda combinations, but it doesn't help. Can you please provide an environment setup file (pip or conda)?

![image](https://github.com/nmndeep/revisiting-at/assets/49342581/9f677db3-26ff-45e5-8637-90894646fdbd)

**Comment by nmndeep** [comment]
[main_py.yml.zip](https://github.com/nmndeep/revisiting-at/files/14423866/main_py.yml.zip)
Here is my environment - works for me here, hope this helps.

**Comment by nmndeep** [comment]
fee free to reopen for any other query
