### ISSUE TITLE
question regarding loading of Vit-small checkpoint 

### ISSUE THREAD

**Issue by legolasflagstaff** [nmndeep/revisiting-at#9]
Hello, 
I downloaded the checkpoint 'ViT-S' which is named **weights_vit_s.pt** on uni tuebingen cloud. 
However, I only succeed to load this checkpoint with **deit_small_patch16_224** architecture from timm, and not **vit_small_patch16_224**. 
Is this expected? 
Best :-)

**Comment by nmndeep** [comment]
Hey,
Yes as the architectures are same for ViT and DeiT this works, for some models in the paper we had to use pretrained DeiT's from timm as ViT's did not have ImageNet only pretrained models.
hope this helps.
